### PR TITLE
Bring codebase up to date with recent PRs

### PR DESCRIPTION
**Pull request by BradleySappington**
Several tests are failing, we have merged in various PRs including some involving requirements.txt which may fix the fails.

### CODE REVIEW

**Comment by mperrin** [comment]
This doesn’t make sense to me, maybe I’m missing something. This is just my fork from the main repo, why do we need to PR here? it’s out of date because I haven’t bothered to pull/push changes here. ??

**Comment by BradleySappington** [comment]
Yeah, this was actually my first time doing this approach.  I was going to comment and ask you to merge over the most recent changes that I pushed, I then realized I could do it for you (in hopes that I'd save you a button click).  However, it still has to be approved by you, so it really doesn't save any work on your end at all.  Happy to just close out, and ask that you merge the most recent PRs into yours to see if it fixes at least some of the CI errors.

**Comment by mperrin** [comment]
Why does any of the CI care about this? Nothing should be running from my personal fork, it should all be runnng the CI from the main repo? Something isn’t right with the CI if it’s pulling from here… can you say more about why/how it looks like this repo is getting used in the CI?

**Comment by BradleySappington** [comment]
You have a pull request from this branch that is failing the automated tests.  If you update this branch it will automatically update the PR with the changes.

**Comment by mperrin** [comment]
Right, got it, sorry, I’m triple multitasking right now while helping run a conference. Will try to update this PR sometime this week. It’ll probably be cleaner if I do it with a rebase rather than a merge.

**Comment by BradleySappington** [comment]
No need to apologize for the complexities of Git!  Enjoy the conference

**Pull request closed without merging**
